# Generated by Django 5.0.6 on 2024-10-07 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True, verbose_name='Название')),
                ('description', models.CharField(blank=True, max_length=200, null=True, verbose_name='Описание')),
                ('price', models.FloatField(verbose_name='Цена')),
                ('text', models.TextField(verbose_name='Особенности')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Тариф',
                'verbose_name_plural': 'Тарифы',
                'ordering': ['-created'],
            },
        ),
    ]
