# Generated by Django 5.0.6 on 2024-10-07 19:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('familyName', models.CharField(max_length=200, verbose_name='Фамилия')),
                ('firstName', models.CharField(max_length=200, verbose_name='Имя')),
                ('patronymic', models.CharField(blank=True, max_length=200, null=True, verbose_name='Отчество')),
                ('age', models.IntegerField(verbose_name='Возраст')),
                ('englishLevel', models.CharField(choices=[('A0', 'A0'), ('A1', 'A1'), ('A2', 'A2'), ('B1', 'B1'), ('B2', 'B2'), ('C1', 'C1')], max_length=50, verbose_name='Уровень английского')),
                ('experience', models.CharField(choices=[('0', 'Отсутствует'), ('half_year', 'До полугода'), ('year', 'Около года'), ('over_year', 'Больше года')], max_length=50, verbose_name='Опыт изучения')),
                ('phoneNumber', models.CharField(max_length=200, verbose_name='Мобильный телефон')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='LessonDays',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('monday', 'Понедельник'), ('tuesday', 'Вторник'), ('wednesday', 'Среда'), ('thursday', 'Четверг'), ('friday', 'Пятницы'), ('saturday', 'Суббота'), ('sunday', 'Воскресенье')], max_length=50, verbose_name='Учебный день')),
                ('user_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='requests.request')),
            ],
            options={
                'verbose_name': 'Учебный день',
                'verbose_name_plural': 'Учебные дни',
            },
        ),
    ]
