# Generated by Django 5.0.6 on 2024-10-08 20:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0004_rename_familname_request_familyname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessondays',
            name='user_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessonDays', to='requests.request'),
        ),
    ]
